Asterism/config/routes.rb
Asterism::Application.routes.draw do
  get "pages/login"
  get "feeds/get_data"

  post   "feeds/xml_upload",       to: "feeds#xml_upload",  as: "xml_upload"
  delete "/feeds/unsubscribe/:id", to: "feeds#unsubscribe", as: "unsubscribe"

  get    "/entries/star/:id",    to: "entries#star",   as: "star_entry"
  delete "/entryies/unstar/:id", to: "entries#unstar", as: "unstar_entry"

  get    "/entries/read/:id",    to: "entries#read",   as: "read_entry"
  delete "/entryies/unread/:id", to: "entries#unread", as: "unread_entry"

  get    "/friend_feeds/:friend_id",           to: "friend_feeds#index", as: "friend_feeds_index"
  get    "/friend_feeds/:friend_id/:feed_id",  to: "friend_feeds#show",  as: "friend_feeds_show"

  resources :entries

  resources :feeds

  root :to => 'pages#login'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

Asterism/app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :author, :categories, :content, :feed_id, :published, :summary, :title, :url, :user_id
  belongs_to :feed
  # for star
  has_many :stared_entries
  has_many :users, :through => :stared_entries
  # for read
  has_many :read_entries
  has_many :users, :through => :read_entries
end

Asterism/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
     render json: {entry: @entry}
  end
  
  def star
    @entry = Entry.find(params[:id])
    current_user.stared_entries.create!(entry_id: params[:id])

    render json: {entry: @entry, type: "star"}
  end
  def unstar
    @entry = Entry.find(params[:id])
    @star = current_user.stared_entries.find_by_entry_id(params[:id])
    @star.destroy if @star

    render json: {entry: @entry, type: "star"}
  end
  def read
    @entry = Entry.find(params[:id])
    current_user.read_entries.create!(entry_id: params[:id])

    render json: {entry: @entry, type: "read"}
  end
  def unread
    @entry = Entry.find(params[:id])
    @read = current_user.read_entries.find_by_entry_id(params[:id])
    @read.destroy if @read

    render json: {entry: @entry, type: "read"}
  end
end

Asterism/app/helpers/entries_helper.rb
module EntriesHelper
	# usage: 
	#   link_to_next_page(@items)
	#   link_to_next_page(@items, :remote => true)  # Ajax
	def link_to_next_page(scope, name, options = {}, &block)
		param_name = options.delete(:param_name) || Kaminari.config.param_name
		link_to_unless scope.last_page?, name, {param_name => (scope.current_page + 1)}, options.merge(:rel => 'next') do
			block.call if block
		end
	end
end

Asterism/app/views/entries/_entry.html.erb
<div class="outline">
	<h3><%= link_to entry.title, entry.url, :target => "_blank" %></h3>
	<p><%= entry.author %></p>
	<div class="pull-right"><%= entry.published %></div>
	<% if entry.content == nil %>
		<td><%= entry.summary %></td>
	<% end %>
	<td><%= entry.content.to_s.gsub(/\&lt;!--[\s\S]*?-->/, '').gsub(/<div[\s\S]*?>/, '').gsub(/<\/div>/, '').try(:html_safe) %></td>
		<!--td><%= entry.categories %></td-->
	<hr>
	<div class="row displaySocialButtons">
		<div class="span2" id="entry-star-<%= entry.id %>">
			<% if entry.stared_entries.find_by_user_id(current_user.id) == nil %>
				<%= link_to content_tag(:i, "", :class => "icon-star-empty")+'add star', star_entry_path(entry), :class => "btn btn-mini", :remote => true %>
				<%= link_to content_tag(:i, "", :class => "icon-star")+'remove star', unstar_entry_path(entry), method: :delete, :style => "display:none;", :class => "btn btn-mini", :remote => true %>
			<% else %>
				<%= link_to content_tag(:i, "", :class => "icon-star-empty")+'add star', star_entry_path(entry), :style => "display:none;", :class => "btn btn-mini", :remote => true %>
				<%= link_to content_tag(:i, "", :class => "icon-star")+'remove star', unstar_entry_path(entry), method: :delete, :class => "btn btn-mini", :remote => true %>
			<% end %>
		</div>
		<div class="span2" id="entry-read-<%= entry.id %>">
			<% if entry.read_entries.find_by_user_id(current_user.id) == nil %>
				<%= link_to content_tag(:i, "", :class => "icon-ok")+'finish read', read_entry_path(entry), :class => "btn btn-mini", :remote => true %>
				<%= link_to content_tag(:i, "", :class => "icon-remove")+'remain unread', unread_entry_path(entry), method: :delete, :style => "display:none;", :class => "btn btn-mini", :remote => true %>
			<% else %>
				<%= link_to content_tag(:i, "", :class => "icon-ok")+'finish read', read_entry_path(entry), :style => "display:none;", :class => "btn btn-mini", :remote => true %>
				<%= link_to content_tag(:i, "", :class => "icon-remove")+'remain unread', unread_entry_path(entry), method: :delete, :class => "btn btn-mini", :remote => true %>
			<% end %>
		</div>

		<div class="span2">
			<!-- twitter -->
			<a href="https://twitter.com/share" class="socialite twitter-share" data-text="<%= entry.title %> via http://asterism.so" data-url="<%= entry.url %>" data-lang="ja">ツイート</a>
		</div>
		<div class="span2">
			<!-- facebook like -->
			<div class="socialite facebook-like" data-href="<%= entry.url %>" data-send="false" data-layout="button_count" data-width="450" data-show-faces="true"></div>
		</div>
		<div class="span2">
			<!-- google plus -->
			<div class="socialite googleplus-one" data-size="medium" data-annotation="inline" data-width="300" data-href="<%= entry.url %>"></div>
		</div>
		<div class="span2">
			<!-- hatena bookmark -->
			<a href="http://b.hatena.ne.jp/entry/<%= entry.url %>" class="hatena-bookmark-button" data-hatena-bookmark-title="Asterism" data-hatena-bookmark-layout="standard-balloon" data-hatena-bookmark-lang="ja" title="このエントリーをはてなブックマークに追加"><img src="http://b.st-hatena.com/images/entry-button/button-only@2x.png" alt="このエントリーをはてなブックマークに追加" width="20" height="20" style="border: none;" /></a><script type="text/javascript" src="http://b.st-hatena.com/js/bookmark_button.js" charset="utf-8" async="async"></script>
		</div>

	</div>
</div>

Asterism/app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :published %><br />
    <%= f.datetime_select :published %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :feed_id %><br />
    <%= f.number_field :feed_id %>
  </div>
  <div class="field">
    <%= f.label :categories %><br />
    <%= f.text_field :categories %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Asterism/app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

Asterism/app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th>Published</th>
    <th>Author</th>
    <th>Summary</th>
    <th>Content</th>
    <th>Feed</th>
    <th>Categories</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.title %></td>
    <td><%= entry.url %></td>
    <td><%= entry.published %></td>
    <td><%= entry.author %></td>
    <td><%= entry.summary %></td>
    <td><%= entry.content %></td>
    <td><%= entry.feed_id %></td>
    <td><%= entry.categories %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entry', new_entry_path %>

Asterism/app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

Asterism/app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @entry.title %>
</p>

<p>
  <b>Url:</b>
  <%= @entry.url %>
</p>

<p>
  <b>Published:</b>
  <%= @entry.published %>
</p>

<p>
  <b>Author:</b>
  <%= @entry.author %>
</p>

<p>
  <b>Summary:</b>
  <%= @entry.summary %>
</p>

<p>
  <b>Content:</b>
  <%= @entry.content %>
</p>

<p>
  <b>Feed:</b>
  <%= @entry.feed_id %>
</p>

<p>
  <b>Categories:</b>
  <%= @entry.categories %>
</p>


<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>