Asterism/config/routes.rb
Asterism::Application.routes.draw do
  get "pages/login"
  get "feeds/get_data"

  post   "feeds/xml_upload",       to: "feeds#xml_upload",  as: "xml_upload"
  delete "/feeds/unsubscribe/:id", to: "feeds#unsubscribe", as: "unsubscribe"

  get    "/entries/star/:id",    to: "entries#star",   as: "star_entry"
  delete "/entryies/unstar/:id", to: "entries#unstar", as: "unstar_entry"

  get    "/entries/read/:id",    to: "entries#read",   as: "read_entry"
  delete "/entryies/unread/:id", to: "entries#unread", as: "unread_entry"

  get    "/friend_feeds/:friend_id",           to: "friend_feeds#index", as: "friend_feeds_index"
  get    "/friend_feeds/:friend_id/:feed_id",  to: "friend_feeds#show",  as: "friend_feeds_show"

  resources :entries

  resources :feeds

  root :to => 'pages#login'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

Asterism/app/models/feed.rb
class Feed < ActiveRecord::Base
  attr_accessible :created_at, :etag, :feed_url, :id, :last_modified, :site_url, :title, :updated_at
  has_many :user_feeds
  has_many :users, :through => :user_feeds
  has_many :entries
end

Asterism/app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_filter :authenticate_user!
  # GET /feeds
  # GET /feeds.json
  def index
    Resque.enqueue(RunProcessor, session) 
    @feeds = current_user.feeds.all(:order => "last_modified")
    @entries = []
    _entries = []
    if params[:star] != nil
        _ids = [-1]
        current_user.stared_entries.each do |star|
          _ids << star.entry_id
        end
        @feeds.each do |feed|
          if params[:star] == "1"
            _entries.concat(feed.entries.find(:all, :order => "published DESC", :conditions => ["id in (?)", _ids]))
          else
            _entries.concat(feed.entries.find(:all, :order => "published DESC", :conditions => ["id not in (?)", _ids]))
          end
        end
    elsif params[:read] != nil
        _ids = [-1]
        current_user.read_entries.each do |star|
          _ids << star.entry_id
        end
        @feeds.each do |feed|
          if params[:read] == "1"
            _entries.concat(feed.entries.find(:all, :order => "published DESC", :conditions => ["id in (?)", _ids]))
          else
            _entries.concat(feed.entries.find(:all, :order => "published DESC", :conditions => ["id not in (?)", _ids]))
          end
        end
    else
        _ids = [-1]
        current_user.read_entries.each do |read|
          _ids << read.entry_id
        end
        @feeds.each do |feed|
            _entries.concat(feed.entries.all(:limit => 5, :order => "published DESC", :conditions => ["id not in (?)", _ids])) 
        end
    end

    @entries = Kaminari.paginate_array(_entries).page(params[:page]).per(5)

    @newfeed = Feed.new

    $redis = Redis.new(:host => 'localhost', :port => 6379)
    $redis.ping
    friendsIds = $redis.smembers current_user.uid.to_s+"_edges"
    logger.debug(friendsIds)

    @friends = User.find(:all, :conditions => ["uid in (?) and provider = ?", friendsIds, "twitter"])
    logger.debug(@friends)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
      format.js

    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feeds   = current_user.feeds
    @feed    = @feeds.find(params[:id])

    # filter by star
    if params[:star] != nil
      _ids = [-1]
      current_user.stared_entries.each do |star|
        _ids << star.entry_id
      end
      logger.debug(_ids)
      if params[:star] == "1"
        @entries = @feed.entries.page(params[:page]).per(5).order("published DESC").where("id in (?)", _ids)
      else
        @entries = @feed.entries.page(params[:page]).per(5).order("published DESC").where("id not in (?)", _ids)
      end
    # filter by read
    elsif params[:read] != nil
      _ids = [-1]
      current_user.read_entries.each do |read|
        _ids << read.entry_id
      end
      logger.debug(_ids)
      if params[:read] == "1"
        @entries = @feed.entries.page(params[:page]).per(5).order("published DESC").where("id in (?)", _ids)
      else
        @entries = @feed.entries.page(params[:page]).per(5).order("published DESC").where("id not in (?)", _ids)
      end
    # default
    else
      _ids = [-1]
      current_user.read_entries.each do |read|
        _ids << read.entry_id
      end
      @entries = @feed.entries.page(params[:page]).per(5).order("published DESC").where("id not in (?)", _ids)
    end

    @newfeed = Feed.new

    $redis = Redis.new(:host => 'localhost', :port => 6379)
    $redis.ping
    friendsIds = $redis.smembers current_user.uid.to_s+"_edges"
    logger.debug(friendsIds)

    @friends = User.find(:all, :conditions => ["uid in (?) and provider = ?", friendsIds, "twitter"])
    logger.debug(@friends)

    respond_to do |format|
      format.html { render :action => "index" and return }# show.html.erb
      format.json { render json: @feed }
      format.js
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @newfeed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.json
  def create
    _feeds = []
    _feed = Feedzirra::Feed.fetch_and_parse(params[:feed]["feed_url"])
    logger.debug("[Debug]"+_feed.title)
    _feeds << Feed.new(:feed_url => _feed.feed_url, :site_url => _feed.url, :title => _feed.title, :etag => _feed.etag, :last_modified => _feed.last_modified)


    respond_to do |format|
      if Feed.import(_feeds, { :on_duplicate_key_update => [:title, :site_url, :etag, :last_modified ] })
        @feed = Feed.find_by_feed_url(_feed.feed_url)
        logger.debug(@feed)

        _user_feeds = []
        _user_feeds << UserFeed.new(:user_id => current_user.id, :feed_id => @feed.id)
        UserFeed.import(_user_feeds)

        # entries bulk insert
        _entries = [] #Array.newでも可
        _feed.entries.each do |entry|
          logger.debug(entry.summary)
            _entries << Entry.new(:url => entry.url, :content => ActionView::Base.white_list_sanitizer.sanitize(entry.content), :summary => entry.summary, :author => entry.author, :categories => entry.categories, :title => entry.title, :published => entry.published, :feed_id => @feed.id)
        end

        if Entry.import(_entries, { :on_duplicate_key_update => [:title, :published, :author, :summary, :content, :categories, :feed_id]})
          logger.debug("[Debug] feed.id : "+@feed.id.to_s)
          format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
          format.json { render json: @feed, status: :created, location: @feed }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def xml_upload
    _feeds = []
    _rawFeeds = []
    xml_file =  params[:feed][:xml].read
    doc = Nokogiri::XML(xml_file)
    logger.debug(doc)
    doc.root.elements.each do |node|
        if node.node_name.eql? 'body'
            node.elements.each do |node|
                logger.debug(node)
                next if !node.attr("xmlUrl") || node.attr("xmlUrl").match(/^http:\/\/www.google.com\/reader/)
                _feed = Feedzirra::Feed.fetch_and_parse(node.attr("xmlUrl"))
                next if !_feed || !_feed.title || !_feed.url
                _feeds << Feed.new(:feed_url => _feed.feed_url, :site_url => _feed.url, :title => _feed.title, :etag => _feed.etag, :last_modified => _feed.last_modified)
                _rawFeeds << _feed
            end
        end
    end

    respond_to do |format|
      if Feed.import(_feeds, { :on_duplicate_key_update => [:title, :site_url, :etag, :last_modified ] })
        _user_feeds = []
        _entries = []

        _rawFeeds.each do |_feed|
            @feed = Feed.find_by_feed_url(_feed.feed_url)
            logger.debug(@feed)
            _user_feeds << UserFeed.new(:user_id => current_user.id, :feed_id => @feed.id)


            _feed.entries.each do |entry|
              logger.debug(entry.summary)
                _entries << Entry.new(:url => entry.url, :content => ActionView::Base.white_list_sanitizer.sanitize(entry.content), :summary => entry.summary, :author => entry.author, :categories => entry.categories, :title => entry.title, :published => entry.published, :feed_id => @feed.id)
            end
        end

        UserFeed.import(_user_feeds)


        # entries bulk insert
        if Entry.import(_entries, { :on_duplicate_key_update => [:title, :published, :author, :summary, :content, :categories, :feed_id]})
          logger.debug("[Debug] feed.id : "+@feed.id.to_s)
          format.html { redirect_to "/", notice: 'Feed was successfully created.' }
          format.json { render json: @feed, status: :created, location: @feed }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end
  def unsubscribe
      @feed = Feed.find(params[:id])
      @user_feed = current_user.user_feeds.find_by_feed_id(params[:id])
      logger.debug(@user_feed)
      @user_feed.destroy if @user_feed

      render json: {feed: @feed, type: "unsubscribe"}

  end

  def get_data
    begin
      @client = Client.make(session[:token], session[:secret])
      #Twitter.followers('azihsoyn'))
      t = TwitterGetData.new @client
      friends = User.find_by_uid(t.getEdgesFromDB(@client.current_user.id), :conditions => ["provider = ?", "twitter"])
      logger.debug(friends)
      Resque.enqueue(RunProcessor, session) 
      data = @client.current_user #なんか取ってきます
      logger.debug(data)
      render :json => data
    rescue => exc
      render :json => exc
    end
  end

end

Asterism/app/helpers/feeds_helper.rb
module FeedsHelper
end

Asterism/app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :site_url %><br />
    <%= f.text_field :site_url %>
  </div>
  <div class="field">
    <%= f.label :feed_url %><br />
    <%= f.text_field :feed_url %>
  </div>
  <div class="field">
    <%= f.label :etag %><br />
    <%= f.text_field :etag %>
  </div>
  <div class="field">
    <%= f.label :last_modified %><br />
    <%= f.datetime_select :last_modified %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br />
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Asterism/app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

Asterism/app/views/feeds/index.html.erb
<h1><% if params[:id] == nil %>All entries<% else %><%= link_to @feed.title, @feed.site_url, :target => "_blank" %> entries<% end %></h1>

<div id="entries">
<%= render @entries %>
</div>

<br />

<% content_for :feed_list do %>
	<% @feeds.each do |feed| %>
		<li class="dropdown <%= 'active' if params[:id] == feed.id.to_s %>" id="feed-<%= feed.id %>">
		<%= link_to content_tag(:img, "", :src => "https://plus.google.com/_/favicon?domain_url="+feed.site_url)+" "+feed.title, feed ,:style => "display:inline-block" %>
		<a href="#" class="dropdown-toggle" data-toggle="dropdown" style="display:inline-block">
			<!--img src="" class="topBarIcon"-->
			<span><b class="caret"></b></span>
		</a>
		<ul class="dropdown-menu">
			<li><%= link_to content_tag(:i, "", :class => "icon-remove")+"購読解除", unsubscribe_path(feed), :method => "DELETE", :remote => true %></li>
		</ul>
		</li>


	<% end %>
<% end %>

<% content_for :regist do %>
	<%= form_for(@newfeed) do |f| %>
		<% if @newfeed.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@newfeed.errors.count, "error") %> prohibited this feed from being saved:</h2>

				<ul>
					<% @newfeed.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<div class="field">
			<%= f.label :feed_url %><br />
			<%= f.text_field :feed_url, :placeholder => "http://hogehoge.com" %>
			<%= f.submit :class => "btn", :value => "Subscribe" %>
		</div>
	<% end %>
<% end %>

Asterism/app/views/feeds/index.js.erb
$('#entries').append('<%= escape_javascript render(@entries) %>');
$("#view_more").replaceWith("<%= escape_javascript(
    link_to_next_page(@entries, 'more', remote: true, id: 'view_more', class: "btn btn-block btn-large")
) %>");
articles = $('.displaySocialButtons');
setTimeout(updateArticles, 100);

Asterism/app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

Asterism/app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @feed.id %>
</p>

<p>
  <b>Title:</b>
  <%= @feed.title %>
</p>

<p>
  <b>Site url:</b>
  <%= @feed.site_url %>
</p>

<p>
  <b>Feed url:</b>
  <%= @feed.feed_url %>
</p>

<p>
  <b>Etag:</b>
  <%= @feed.etag %>
</p>

<p>
  <b>Last modified:</b>
  <%= @feed.last_modified %>
</p>

<p>
  <b>Created at:</b>
  <%= @feed.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @feed.updated_at %>
</p>


<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

Asterism/app/views/feeds/show.js.erb
$('#entries').append('<%= escape_javascript render(@entries) %>');
$("#view_more").replaceWith("<%= escape_javascript(
    link_to_next_page(@entries, 'more', remote: true, id: 'view_more', class: "btn btn-block btn-large")
) %>");
articles = $('.displaySocialButtons');
setTimeout(updateArticles, 100);