Asterism/config/routes.rb
Asterism::Application.routes.draw do
  get "pages/login"
  get "feeds/get_data"

  post   "feeds/xml_upload",       to: "feeds#xml_upload",  as: "xml_upload"
  delete "/feeds/unsubscribe/:id", to: "feeds#unsubscribe", as: "unsubscribe"

  get    "/entries/star/:id",    to: "entries#star",   as: "star_entry"
  delete "/entryies/unstar/:id", to: "entries#unstar", as: "unstar_entry"

  get    "/entries/read/:id",    to: "entries#read",   as: "read_entry"
  delete "/entryies/unread/:id", to: "entries#unread", as: "unread_entry"

  get    "/friend_feeds/:friend_id",           to: "friend_feeds#index", as: "friend_feeds_index"
  get    "/friend_feeds/:friend_id/:feed_id",  to: "friend_feeds#show",  as: "friend_feeds_show"

  resources :entries

  resources :feeds

  root :to => 'pages#login'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

Asterism/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= content_for?(:title) ? yield(:title) : "Asterism" %></title>
		<%= csrf_meta_tags %>

		<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
		<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
		<![endif]-->

		<%= stylesheet_link_tag "application", :media => "all" %>
		<link href='http://fonts.googleapis.com/css?family=Allura' rel='stylesheet' type='text/css'>

		<!-- For third-generation iPad with high-resolution Retina display: -->
		<!-- Size should be 144 x 144 pixels -->
		<%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

		<!-- For iPhone with high-resolution Retina display: -->
		<!-- Size should be 114 x 114 pixels -->
		<%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

		<!-- For first- and second-generation iPad: -->
		<!-- Size should be 72 x 72 pixels -->
		<%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

		<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
		<!-- Size should be 57 x 57 pixels -->
		<%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

		<!-- For all other devices -->
		<!-- Size should be 32 x 32 pixels -->
		<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
	</head>
	<body>
		<div class="wrapper">
			<div class="navbar navbar-fixed-top">
				<div class="navbar-inner">
					<div class="container">
						<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</a>
						<%= link_to "*Asterism", "/", :class => "brand" %>
						<div class="container nav-collapse">
							<ul class="nav">
								<!--
								<li><%= link_to "Link1", "/path1"  %></li>
								<li><%= link_to "Link2", "/path2"  %></li>
								<li><%= link_to "Link3", "/path3"  %></li>
								-->
							</ul>
							<ul class="nav pull-right">
								<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<!--img src="" class="topBarIcon"-->
									<% if current_user %>
										<img src="<%= current_user.image_url %>" class="prof_image">
										<% if current_user.provider == 'asterism' %>
										<span><%= current_user.email %> <b class="caret"></b></span>
										<% else %>
										<span><%= current_user.name %> <b class="caret"></b></span>
										<% end %>
									<% end %>
								</a>
								<ul class="dropdown-menu">
									<!--
									<li><a href="/users/azihsoyn">プロフィール</a></li> 
									<li><a href="https://dotinstall.com/user/settings">設定変更</a></li>
									<li><a href="/help">ヘルプ</a></li>
									<li class="divider"></li> 
									-->
									<li><%= link_to content_tag(:i, "", :class => "icon-off")+"ログアウト", destroy_user_session_path, :method => "DELETE" %></li>
								</ul>
								</li>
							</ul>
						</div><!--/.nav-collapse -->
					</div>
				</div>
			</div>

			<div class="container header-padding content_end_point">
				<div class="subnav subnav-fixed">
				    <ul class="nav nav-pills">
				    	<!--
				      	<li class="dropdown">
				        	<a class="dropdown-toggle" data-toggle="dropdown" href="#">ボタン <b class="caret"></b></a>
				        	<ul class="dropdown-menu">
				          		<li><a href="#buttonGroups">ボタングループ</a></li>
				          		<li><a href="#buttonDropdowns">ドロップダウンボタン</a></li>
				        	</ul>
				      	</li>
				  		-->
				      	<li class="dropdown pull-right">
				        	<a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-filter"></i>filter <b class="caret"></b></a>
				        	<ul class="dropdown-menu">
				        		<li class="<%= 'active' if params[:star] == "1" %>"><%= link_to content_tag(:i, "", :class => "icon-star")+'filter by star', params[:star] == "1" ? request.path_info : request.path_info+"?star=1" %></li>
				        		<li class="<%= 'active' if params[:star] == "0" %>"><%= link_to content_tag(:i, "", :class => "icon-star-empty")+'filter by no-star', params[:star] == "0" ? request.path_info : request.path_info+"?star=0" %></li>
				        		<li class="<%= 'active' if params[:read] == "1" %>"><%= link_to content_tag(:i, "", :class => "icon-ok")+'filter by read', params[:read] == "1" ? request.path_info : request.path_info+"?read=1" %></li>
				        		<li class="<%= 'active' if params[:read] == "0" %>"><%= link_to content_tag(:i, "", :class => "icon-remove")+'filter by unread', params[:read] == "0" ? request.path_info : request.path_info+"?read=0" %></li>
				        	</ul>
				      	</li>
				      	<!--
				      	<li><a href="#labels">ラベル</a></li>
				      	<li><a href="#badges">バッジ</a></li>
				      	<li><a href="#typography">タイポグラフィ</a></li>
				      	<li><a href="#thumbnails">サムネイル</a></li>
				      	<li><a href="#alerts">アラート</a></li>
				      	<li><a href="#progress">プログレスバー</a></li>
				      	<li><a href="#misc">その他</a></li>
				      	-->
				    </ul>
				</div>
				<div class="row">
					<div class="span3">
						<div class="well sidebar-nav my_affix">
							<!-- 登録dropdown -->
							<div class="btn-group">
								<button class="btn btn-small dropdown-toggle" data-toggle="dropdown">登録 <span class="caret"></span></button>
								<ul class="dropdown-menu" style="padding:17px;">
									<li>
									<form accept-charset="UTF-8" action="/feeds" class="new_feed" id="new_feed" method="post">
										<div class="input-append">
											<!--
											<input type="text" class="span2 search-query" placeholder="http://hogehoge.com">
											<button type="submit" class="btn">購読</button>
											-->
											<%= yield :regist%>
											<%= form_for @newfeed, url: {controller:"feeds", action: "xml_upload"} do |f| %>
												<%= f.file_field :xml %>
												<%= f.submit :class => "btn", :value => "Subscribe" %>
											<% end %>
										</div>
									</form>
									</li>
								</ul>
							</div>
							<ul class="nav nav-list">
								<li class="nav-header"><i class="icon-list-alt"></i>Feed list</li>
								<li class="<%= 'active' if params[:id] == nil && params[:friend_id] == nil %>"><%= link_to content_tag(:img, "", :src => "https://plus.google.com/_/favicon?domain_url=")+" All", "/" %></li>
								<%= yield :feed_list %>
								<li class="divider"></li> 
								<li class="nav-header"><i class="icon-user"></i>Follow list</li>
								<% @friends.each do |friend| %>
									<li class="<%= 'active' if params[:friend_id] == friend.id.to_s && params[:feed_id] == nil %>"><%= link_to content_tag(:img, "", :src => friend.image_url, :class => "prof_image")+" "+friend.name, friend_feeds_index_path(friend) %></li>
									<ul class="nav nav-list">
										<% friend.feeds.each do |f_feed| %>
											<li class="<%= 'active' if params[:friend_id] == friend.id.to_s && params[:feed_id] == f_feed.id.to_s %>"><%= link_to content_tag(:img, "", :src => "https://plus.google.com/_/favicon?domain_url="+f_feed.site_url)+" "+f_feed.title, friend_feeds_show_path(friend, f_feed) %></li>
										<% end %>
									</ul>
								<% end %>

							</ul>
						</div><!--/.well -->
					</div><!--/span-->
					<div class="span9">
						<%= bootstrap_flash %>
						<%= yield %>
						<%= link_to_next_page(@entries, 'more', remote: true, id: 'view_more', class: "btn btn-block btn-large") %>
					</div>
				</div><!--/row-->


			</div> <!-- /container -->
		</div>


		<%= render "footer" %>

		<!-- Javascripts
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<%= javascript_include_tag "application" %>
		<script type="text/javascript">
			$('.dropdown-toggle').dropdown();
			$('.dropdown-menu').find('form').click(function (e) {
				e.stopPropagation();
			});
			$(function(){
				$('a[data-remote="true"]').on('ajax:success', function(e, data, status, xhr){
					if(data.type == "unsubscribe"){
						$("#feed-"+data.feed.id).fadeOut('slow');
					}else if(data.type == "star"){
						$("#entry-star-"+data.entry.id+" a").toggle();
					}else{
						$("#entry-read-"+data.entry.id+" a").toggle();
					}
				})
			})
			// side bar
			setTimeout(function () {
				var $window = $(window)
				$('.my_affix').affix({
					offset: {
						top: function () { return $window.width() <= 980 ? 90 : 0 }
						, bottom: 270
					}
				})
			}, 100)
			var	articles = $('.displaySocialButtons'), socialised = { }, win = $(window), updateArticles, onUpdate, updateTimeout;

			var updateArticles = function()
			{
				// viewport bounds
				var	wT = win.scrollTop(),
				wL = win.scrollLeft(),
				wR = wL + win.width(),
				wB = wT + win.height();
				// check which articles are visible and socialise!
				for (var i = 0; i < articles.length; i++) {
					if (socialised[i]) {
						continue;
					}
					// article bounds
					var	art = $(articles[i]),
					aT = art.offset().top,
					aL = art.offset().left,
					aR = aL + art.width(),
					aB = aT + art.height();
					// vertial point inside viewport
					if ((aT >= wT && aT <= wB) || (aB >= wT && aB <= wB)) {
						// horizontal point inside viewport
						if ((aL >= wL && aL <= wR) || (aR >= wL && aR <= wR)) {
							socialised[i] = true;
							Socialite.load(articles[i]);
						}
					}
				}
			};

			var onUpdate = function()
			{
				if (updateTimeout) {
					clearTimeout(updateTimeout);
				}
				updateTimeout = setTimeout(updateArticles, 100);
			};
			$(document).ready(function()
			{

				var footer = $('.footer');
				Socialite.load(footer);

				win.on('resize', onUpdate).on('scroll', onUpdate);

				setTimeout(updateArticles, 100);

			});
		</script>
		<div id="fb-root"></div>

  </body>
</html>

Asterism/app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= content_for?(:title) ? yield(:title) : "Asterism" %></title>
		<%= csrf_meta_tags %>

		<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
		<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
		<![endif]-->

		<%= stylesheet_link_tag "application", :media => "all" %>
		<link href='http://fonts.googleapis.com/css?family=Allura' rel='stylesheet' type='text/css'>

		<!-- For third-generation iPad with high-resolution Retina display: -->
		<!-- Size should be 144 x 144 pixels -->
		<%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

		<!-- For iPhone with high-resolution Retina display: -->
		<!-- Size should be 114 x 114 pixels -->
		<%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

		<!-- For first- and second-generation iPad: -->
		<!-- Size should be 72 x 72 pixels -->
		<%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

		<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
		<!-- Size should be 57 x 57 pixels -->
		<%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

		<!-- For all other devices -->
		<!-- Size should be 32 x 32 pixels -->
		<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
	</head>
	<body>
		<div class="wrapper">
			<div class="navbar navbar-fixed-top">
				<div class="navbar-inner">
					<div class="container">
						<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</a>
						<%= link_to "*Asterism", "/", :class => "brand" %>
						<div class="container nav-collapse">
						</div><!--/.nav-collapse -->
					</div>
				</div>
			</div>

			<div class="container-fluid" style="padding-top: 60px; padding-bottom: 30px;">
				<div class="push"><!--//--></div>
				<div class="row-fluid">
					<div class="span12">
						<%= bootstrap_flash %>
						<div class="jumbotron narrow">
						<%= yield %>
						</div>
					</div>
				</div><!--/row-->
			</div> <!-- /container -->
		</div>

		<%= render "footer" %>

		<!-- Javascripts
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<%= javascript_include_tag "application" %>
		<script type="text/javascript">
			$('.dropdown-toggle').dropdown();
			$('.dropdown-menu').find('form').click(function (e) {
				e.stopPropagation();
			});
			$(document).ready(function(){
				Socialite.load();
			});
		</script>
		<div id="fb-root"></div>
		

  </body>
</html>